services:
  - type: web
    name: stock-market-backend
    env: python
    plan: free
    buildCommand: 
      - pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:5000
    envVars:
      - key: PORT
        value: 5000
